[2024-06-16T08:01:21.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T08:01:21.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: status_dag_v2.failed_state manual__2024-06-16T08:01:20.902939+00:00 [queued]>
[2024-06-16T08:01:21.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: status_dag_v2.failed_state manual__2024-06-16T08:01:20.902939+00:00 [queued]>
[2024-06-16T08:01:21.368+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-16T08:01:21.384+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): failed_state> on 2024-06-16 08:01:20.902939+00:00
[2024-06-16T08:01:21.392+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2507) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-16T08:01:21.393+0000] {standard_task_runner.py:63} INFO - Started process 2508 to run task
[2024-06-16T08:01:21.392+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'status_dag_v2', 'failed_state', 'manual__2024-06-16T08:01:20.902939+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/skipDAG.py', '--cfg-path', '/tmp/tmpec0ok5ov']
[2024-06-16T08:01:21.394+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask failed_state
[2024-06-16T08:01:21.473+0000] {task_command.py:426} INFO - Running <TaskInstance: status_dag_v2.failed_state manual__2024-06-16T08:01:20.902939+00:00 [running]> on host 15cc12e76742
[2024-06-16T08:01:21.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ariflow' AIRFLOW_CTX_DAG_ID='status_dag_v2' AIRFLOW_CTX_TASK_ID='failed_state' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T08:01:20.902939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T08:01:20.902939+00:00'
[2024-06-16T08:01:21.616+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T08:01:21.655+0000] {skipDAG.py:9} ERROR - Failed....
[2024-06-16T08:01:21.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T08:01:21.656+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skipDAG.py", line 10, in fail_state
    raise Exception('Failed....')
Exception: Failed....
[2024-06-16T08:01:21.673+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=status_dag_v2, task_id=failed_state, run_id=manual__2024-06-16T08:01:20.902939+00:00, execution_date=20240616T080120, start_date=20240616T080121, end_date=20240616T080121
[2024-06-16T08:01:21.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task failed_state (Failed....; 2508)
[2024-06-16T08:01:21.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T08:01:21.773+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T08:01:21.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
