[2024-06-16T08:10:38.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T08:10:38.540+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: status_dag_v3.failed_state manual__2024-06-16T08:10:37.971431+00:00 [queued]>
[2024-06-16T08:10:38.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: status_dag_v3.failed_state manual__2024-06-16T08:10:37.971431+00:00 [queued]>
[2024-06-16T08:10:38.553+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-16T08:10:38.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): failed_state> on 2024-06-16 08:10:37.971431+00:00
[2024-06-16T08:10:38.575+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'status_dag_v3', 'failed_state', 'manual__2024-06-16T08:10:37.971431+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/skipDAG.py', '--cfg-path', '/tmp/tmpq4e9m248']
[2024-06-16T08:10:38.577+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask failed_state
[2024-06-16T08:10:38.578+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3027) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-16T08:10:38.579+0000] {standard_task_runner.py:63} INFO - Started process 3028 to run task
[2024-06-16T08:10:38.641+0000] {task_command.py:426} INFO - Running <TaskInstance: status_dag_v3.failed_state manual__2024-06-16T08:10:37.971431+00:00 [running]> on host 15cc12e76742
[2024-06-16T08:10:38.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ariflow' AIRFLOW_CTX_DAG_ID='status_dag_v3' AIRFLOW_CTX_TASK_ID='failed_state' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T08:10:37.971431+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T08:10:37.971431+00:00'
[2024-06-16T08:10:38.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T08:10:38.811+0000] {skipDAG.py:9} ERROR - Failed....
[2024-06-16T08:10:38.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T08:10:38.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/skipDAG.py", line 10, in fail_state
    raise Exception('Failed....')
Exception: Failed....
[2024-06-16T08:10:38.826+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=status_dag_v3, task_id=failed_state, run_id=manual__2024-06-16T08:10:37.971431+00:00, execution_date=20240616T081037, start_date=20240616T081038, end_date=20240616T081038
[2024-06-16T08:10:38.839+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task failed_state (Failed....; 3028)
[2024-06-16T08:10:38.881+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T08:10:38.908+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T08:10:38.916+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
